config/routes.rb
Rails.application.routes.draw do
  root "home_page#index"

  resources :pacientes do
    resources :enderecos
  end
  resources :medicos
  resources :consulta_medicas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consulta_medica.rb
class ConsultaMedica < ApplicationRecord
  belongs_to :medico
  belongs_to :paciente

  STATUSES = %w(Agendada Cancelada Atendida)

  validates :data, presence: true
  validates :data, inclusion: { in: lambda { |record| Date.today..Date::Infinity.new }, message: "inválida!" }


  validates :horario, presence: true, uniqueness: true
  validate :horario_fora_do_expediente
  validate :horario_reservado

  private
  #Valida se o horário já esta reservado
  def horario_reservado
    agendas_no_mesmo_horario = ConsultaMedica.where(horario: horario.strftime("%H:%M"), data: data)
    if !agendas_no_mesmo_horario.empty?
      errors.add(:horario, "já está reservado")
    end
  end


  private
  #Valida se o horário da consulta está no intervalo de 8:00 as 16:00
  def horario_fora_do_expediente
    aberto = Time.parse("8:00").strftime("%H:%M")
    fechado = Time.parse("16:00").strftime("%H:%M")
    fora_do_expediente = horario.strftime("%H:%M") < aberto || horario.strftime("%H:%M") > fechado
    puts(horario.strftime("%H:%M"))
    if fora_do_expediente
      errors.add(:horario, "deve estar entre 8:00 e 16:00")
    end
  end

end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :paciente

  validates :cep, presence: true,  format: { with: /\A[0-9]{8}\z/, message: "só aceita números" }
  validates :cidade, presence: true, length: { minimum: 3, maximum: 20}
  validates :bairro, presence: true, length: { minimum: 3, maximum: 20}
  validates :logradouro, presence: true, length: { minimum: 3, maximum: 30}

end

app/models/medico.rb
class Medico < ApplicationRecord

  has_many :consulta_medicas

  validates :nome_completo, presence: true, length: { minimum: 3, maximum: 30}, format: { with: /\A[^0-9]+\z/ }
  validates :cpf, presence: true, uniqueness: true, format: { with: /\A\d{11,11}\z/}
  validates :email, presence: true,  uniqueness: true, length: { minimum: 4, maximum: 20}, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.com\z/i }
  validates :especialidade, presence: true, length: { minimum: 3, maximum: 30}, format: { with: /\A[^0-9]+\z/ }
  validates :crm, presence: true, uniqueness: true, length: { minimum: 6, maximum: 6}

end

app/models/paciente.rb
class Paciente < ApplicationRecord
  has_one :endereco
  has_many :consulta_medicas

  accepts_nested_attributes_for :endereco , update_only: true

  validates :nome_completo, presence: true, length: { minimum: 3, maximum: 30}, format: { with: /\A[^0-9]+\z/ }
  validates :data_nascimento, presence: true, length: { minimum: 10 , maximum: 10}
  validate :data_nascimento_validation


  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11 , maximum: 11}, format: { with: /\A\d{11,11}\z/}
  validates :email, presence: true, uniqueness: true, length: { minimum: 4, maximum: 30}, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.com\z/i }

  def data_nascimento_validation
    if data_nascimento.present? && data_nascimento > Date.today
      errors.add(:data_nascimento, "não pode ser posterior a hoje")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consulta_medicas_controller.rb
class ConsultaMedicasController < ApplicationController
  def index
    @consulta_medicas = ConsultaMedica.all
  end

  def show
    @consulta_medica = ConsultaMedica.find(params[:id])
    @data_formatada = @consulta_medica.data.strftime("%d-%m-%Y")
  end

  def new
    @consulta_medica = ConsultaMedica.new
  end

  def create
    @consulta_medica = ConsultaMedica.new(consulta_medica_params)

    if @consulta_medica.save
      redirect_to @consulta_medica
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @consulta_medica = ConsultaMedica.find(params[:id])
  end

  def update
    @consulta_medica = ConsultaMedica.find(params[:id])

    if @consulta_medica.update(consulta_medica_params)
      redirect_to @consulta_medica
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def consulta_medica_params
    params.require(:consulta_medica).permit(:data, :horario, :paciente_id, :medico_id, :status)
  end
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  def index
    @medicos = Medico.all
  end
  def show
    @medico = Medico.find(params[:id])
    @cpf_formatado = @medico.cpf.to_s.gsub(/(\d{3})(\d{3})(\d{3})(\d{2})/, '\1.\2.\3-\4')
    @consultas_agendadas = @medico.consulta_medicas.where(status: 'Agendada')
  end

  def new
    @medico = Medico.new

  end

  def create
    @medico = Medico.new(medico_params)

    if @medico.save
      redirect_to @medico
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @medico = Medico.find(params[:id])
  end

  def update
    @medico = Medico.find(params[:id])

    if @medico.update(medico_params)
      redirect_to @medico
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def medico_params
      params.require(:medico).permit(:nome_completo, :cpf, :email, :especialidade, :crm)
    end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  def index
    @pacientes = Paciente.all
  end

  def show
    @paciente = Paciente.find(params[:id])
    @cpf_formatado = @paciente.cpf.to_s.gsub(/(\d{3})(\d{3})(\d{3})(\d{2})/, '\1.\2.\3-\4')
    @data_formatada = @paciente.data_nascimento.strftime("%d-%m-%Y")
    @cep_formatado = @paciente.endereco.cep.insert(5, '-')
    @cidade_formatada = @paciente.endereco.cidade.mb_chars.titleize.to_s
    @bairro_formatado = @paciente.endereco.bairro.mb_chars.titleize.to_s
    @logradouro_formatado = @paciente.endereco.logradouro.mb_chars.titleize.to_s
    @complemento_formatado = @paciente.endereco.complemento.mb_chars.titleize.to_s
  end

  def new
    @paciente = Paciente.new
    @paciente.build_endereco
  end

  def create
    @paciente = Paciente.new(paciente_params)


    if @paciente.save
      redirect_to @paciente
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @paciente = Paciente.find(params[:id])
  end

  def update
    @paciente = Paciente.find(params[:id])

    if @paciente.update(paciente_params)
      redirect_to @paciente
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def paciente_params
      params.require(:paciente).permit(:nome_completo, :data_nascimento, :cpf, :email, :endereco_attributes =>[:cep, :cidade, :bairro, :logradouro, :complemento])

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consulta_medicas_helper.rb
module ConsultaMedicasHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/consulta_medicas/_form.html.erb
<%= form_with model: consulta_medica do |form| %>

  <div>
    <%= form.label :data %><br>
    <%= form.date_field :data %>
    <% consulta_medica.errors.full_messages_for(:data).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
  </div>

  <div>
    <%= form.label :horario %><br>
    <%= form.time_field :horario %>
    <% consulta_medica.errors.full_messages_for(:horario).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :paciente %>
  <%= form.collection_select :paciente_id, Paciente.all, :id, :nome_completo %>
  </div>

  <div>
    <%= form.label :medico %>
  <%= form.collection_select :medico_id, Medico.all, :id, :nome_completo %>
  </div>

  <div>
  <%= form.label :status %>
    <%= form.select :status, options_for_select(ConsultaMedica::STATUSES), {} %>
  </div>




  <div>
    <br><%= form.submit %>
  </div>
<% end %>

app/views/consulta_medicas/edit.html.erb
<h1>Editar Consultas Médica</h1>

<%= render "form", consulta_medica: @consulta_medica %>

app/views/consulta_medicas/index.html.erb
<h1>Consultas Médicas</h1>

<ul>
  <% @consulta_medicas.each do |consulta_medica| %>
       <li>
         <%= link_to consulta_medica.data.strftime("%d-%m-%Y"), consulta_medica %>
       </li>
  <% end %>
</ul>

<%= link_to "Nova Consulta Médica", new_consulta_medica_path %>

app/views/consulta_medicas/new.html.erb
<h1>Nova Consultas Médica</h1>

<%= render "form", consulta_medica: @consulta_medica %>

app/views/consulta_medicas/show.html.erb
<h1>Consulta</h1>

<h3>Data: <%= @data_formatada %></h3>
<h3>Horário: <%= @consulta_medica.horario.strftime("%H:%M") %></h3>
<h3>Paciente: <%= @consulta_medica.paciente.nome_completo %></h3>
<h3>Médico: <%= @consulta_medica.medico.nome_completo %></h3>
<h3>Status: <%= @consulta_medica.status %></h3>

<%= link_to "Voltar", consulta_medicas_url %>
<%= link_to "Editar", edit_consulta_medica_path(@consulta_medica)%>

app/views/enderecos/_form.html.erb
<%= form_with model: [ @paciente, @paciente.enderecos.build ] do |form| %>
  <div>
    <%= form.label :cep %><br>
    <%= form.text_field :cep %>
  </div>

  <div>
    <%= form.label :cidade %><br>
    <%= form.text_field :cidade %>
  </div>

  <div>
    <%= form.label :bairro %><br>
    <%= form.text_field :bairro %>
  </div>

  <div>
    <%= form.label :cep %><br>
    <%= form.text_field :cep %>
  </div>

  <div>
    <br><%= form.submit %>
  </div>
<% end %>

app/views/home_page/index.html.erb
<h1>Consulta Sim</h1>

<h2>Bem vindo, o que deseja fazer?</h2>

<p><%= link_to "Paciente", pacientes_url %></p>
<p><%= link_to "Médico", medicos_url %></p>
<p><%= link_to "Consulta Médica", consulta_medicas_url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsultaSim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/medicos/_form.html.erb
<%= form_with model: medico do |form| %>
  <div>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome_completo %>
    <% medico.errors.full_messages_for(:nome_completo).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
  </div>

  <div>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
    <% medico.errors.full_messages_for(:cpf).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% medico.errors.full_messages_for(:email).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :especialidade %><br>
    <%= form.text_field :especialidade %>
    <% medico.errors.full_messages_for(:especialidade).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :crm %><br>
    <%= form.text_field :crm %>
    <% medico.errors.full_messages_for(:crm).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <br><%= form.submit %>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<h1>Editar Médico</h1>

<%= render "form", medico: @medico%>

app/views/medicos/index.html.erb
<h1>Médicos</h1>
<ul>
  <% @medicos.each do |medico| %>
    <li>
      <%= link_to medico.nome_completo, medico %>
      </a>
    </li>
  <% end %>
</ul>
<%= link_to "Novo Médico", new_medico_path %>

app/views/medicos/new.html.erb
<h1>Novo Médico</h1>

<%= form_with model: @medico do |form| %>
  <div>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome_completo %>
    <% @medico.errors.full_messages_for(:nome_completo).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
    <% @medico.errors.full_messages_for(:cpf).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @medico.errors.full_messages_for(:email).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :especialidade %><br>
    <%= form.text_field :especialidade%>
    <% @medico.errors.full_messages_for(:especialidade).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :crm %><br>
    <%= form.text_field :crm %>
    <% @medico.errors.full_messages_for(:crm).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <br><%= form.submit %>
  </div>


<% end %>

app/views/medicos/show.html.erb
<h1>Médico</h1>

<h3>Nome: <%= @medico.nome_completo %></h3>
<h3>CPF: <%= @cpf_formatado %></h3>
<h3>E-mail: <%= @medico.email %></h3>
<h3>Especialidade: <%= @medico.especialidade %></h3>
<h3>CRM: <%= @medico.crm %></h3>

<% if @consultas_agendadas.present? %>
  <h2>Consultas agendadas</h2>
  <table>
    <tr>
      <th>Data</th>
      <th>Paciente</th>
      <th>Estado</th>
    </tr>
    <% @consultas_agendadas.each do |consulta| %>
      <tr>
        <td><%= consulta.data %></td>
        <td><%= consulta.paciente.nome_completo %></td>
        <td><%= consulta.status %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Não há consultas agendadas para esse médico.</p>
<% end %>


<ul>
  <li>
    <%= link_to "Editar", edit_medico_path(@medico) %>
  </li>
</ul>

app/views/pacientes/_form.html.erb
<%= form_with model: paciente do |form| %>
  <div>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome_completo %>
    <% paciente.errors.full_messages_for(:nome_completo).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
  </div>

  <div>
    <%= form.label :data_nascimento %><br>
    <%= form.date_field :data_nascimento %>
    <% paciente.errors.full_messages_for(:data_nascimento).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
    <% paciente.errors.full_messages_for(:cpf).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% paciente.errors.full_messages_for(:email).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <%= form.fields_for :endereco do |formu| %>
    <div>
      <%= formu.label :cep %><br>
      <%= formu.text_field :cep %>
      <% paciente.errors[:endereco_attributes].each do |message| %>
        <div>
          <%= message %>
        </div>
  <% end %>
    </div>
    <div>
      <%= formu.label :cidade %><br>
      <%= formu.text_field :cidade %>
    </div>

    <div>
      <%= formu.label :bairro %><br>
      <%= formu.text_field :bairro %>
    </div>

    <div>
      <%= formu.label :logradouro %><br>
      <%= formu.text_field :logradouro %>
    </div>

    <div>
      <%= formu.label :complemento %><br>
      <%= formu.text_field :complemento %>
    </div>

  <% end %>

  <div>
    <br><%= form.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editar Paciente</h1>

<%= render "form", paciente: @paciente %>

app/views/pacientes/index.html.erb
<h1>Pacientes</h1>
<ul>
  <% @pacientes.each do |paciente| %>
    <li>
      <%= link_to paciente.nome_completo, paciente %>
    </li>
  <% end %>
</ul>

<%= link_to "Novo Paciente", new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>Novo Paciente</h1>

<%= render "form", paciente: @paciente%>

app/views/pacientes/show.html.erb
<h1>Paciente</h1>

<h3>Nome: <%= @paciente.nome_completo %></h3>
<h3>Data Nascimento: <%= @data_formatada %></h3>
<h3>CPF: <%= @cpf_formatado %></h3>
<h3>Email: <%= @paciente.email %></h3>
<h3>CEP: <%= @cep_formatado %></h3>
<h3>Cidade: <%= @cidade_formatada %></h3>
<h3>Bairro: <%= @bairro_formatado %></h3>
<h3>Logradouro: <%= @logradouro_formatado %></h3>
<h3>Complemento: <%= @complemento_formatado %></h3>


<ul>
  <li>
    <%= link_to "Edit", edit_paciente_path(@paciente) %>
  </li>
</ul>